@startuml
'https://plantuml.com/sequence-diagram

autonumber

Customer -> "Ticketing API" : **POST /troubleTicket** Création du ticket avec ses références
"Ticketing API" --> Customer : **HTTP 201** Identifiant du ticket
... ...
Customer -> "Ticketing API" : **GET /troubleTicket/{id}** Récupération du ticket
"Ticketing API" --> Customer : **HTTP 200** Suivi du ticket
... ...
Customer -> "Ticketing API" : **PATCH /troubleTicket/{id}** Ajout de notes
"Ticketing API" --> Customer : **HTTP 200** Ticket mis à jour
... ...
Customer -> "Ticketing API" : **POST /hub** Abonnement aux notifications \n pour une requete du client avec url de callback
    "Ticketing API" --> Customer : **HTTP 201** Abonnement effectué
... ...
"Ticketing API" -> "Ticketing API" : Maj du ticket
... ...
"Ticketing API" -> "Customer" : **POST callbackUrl/troubleTicketStatusChangeEvent** \n avec évènement de changement d'état
"Customer" --> "Ticketing API" : **HTTP 201** Evènement reçu

@enduml
