@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class TroubleTicket  <<Pivot>> {
    id : String
    href : String
    creationDate : DateTime
    description : String
    expectedResolutionDate : DateTime
    externalId : String
    lastUpdate : DateTime
    name : String
    resolutionDate : DateTime
    status : TroubleTicketStatusType
    statusChangeDate : DateTime
    statusChangeReason : String
    ticketType : String
    complexity: String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TroubleTicketStatusType <<Enumeration>> {
    acknowledged
    rejected
    pending
    held
    inProgress
    cancelled
    closed
    resolved
}

class Note  {
    author : String
    date : DateTime
    id : String
    text : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class TroubleTicketRelationship  <<Ref>> {
    href : String
    id : String
    name : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRef  {
    id : String
    href : Uri
    name: String
    mimeType : String
    size : Quantity
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class StatusChange  {
    changeDate : DateTime
    changeReason : String
    status : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedEntity  {
    href : String
    id : String
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

TroubleTicket -right[hidden]-> TroubleTicketStatusType

Note "0..*" <-left-* TroubleTicket : note

AttachmentRef "0..*" <--* TroubleTicket : attachment

TroubleTicket *-->  "0..*" StatusChange : statusChange

TroubleTicket *-->  "0..*" TroubleTicketRelationship : troubleTicketRelationship

TroubleTicket *-->  "0..*" RelatedEntity : relatedEntity

@enduml